on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: Create Release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v5

      - name: 🚀 Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 🛠 Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get latest release commit SHA
        if: env.latest_nightly_commit == null
        run: |
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "latest_release=${latest_release}" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.latest_release }}
          includeInvalidCommits: true

      - name: 🚀 Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/*.jar
            target/*.deb
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
